{
 "title": "OctoRPKI - GoRTR",
 "description": "Shows the status of RPKI validation and the RTR server health.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_validator",
    "label": "Validator node",
    "query": "label_values(last_stable_validation, instance)"
   },
   {
    "name": "node_rtr",
    "label": "RTR node",
    "query": "label_values(rpki_roas, instance)"
   }
  ]
 },
 "panels": [
  { "title": "RTR server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IPv4 ROAs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(rpki_roas{filtered=\"filtered\",ip_version=\"ipv4\", instance=\"$node_rtr\"}) by (ip_version)",
     "legendFormat": "{{ ip_version }}"
    }
   ]
  },
  {
   "title": "IPv6 ROAs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(rpki_roas{filtered=\"filtered\",ip_version=\"ipv6\", instance=\"$node_rtr\"}) by (ip_version)",
     "legendFormat": "{{ ip_version }}"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rtr_clients{instance=\"$node_rtr\"})"
    }
   ]
  },
  {
   "title": "Last fetch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(time() - rpki_refresh{instance=\"$node_rtr\"})"
    }
   ]
  },
  {
   "title": "RTR PDU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rtr_pdus{instance=\"$node_rtr\"}[1m])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Message count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rtr_pdus{instance=\"$node_rtr\"}) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "ROAs per TAL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(roas{ta!=\"\",instance=\"$node_validator\"}) by (ta) > 0",
     "legendFormat": "{{ ta }}"
    }
   ]
  },
  {
   "title": "Last validation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(time()-last_stable_validation{instance=\"$node_validator\"}) < 1000000"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(file_count_sia{instance=\"$node_validator\"}) by (address, type)",
     "legendFormat": "{{ type }} {{ address }}"
    }
   ]
  }
 ]
}